### ISSUE TITLE
Initial Commit

### ISSUE THREAD

**Issue by fvella** [LACSFUB/CSPID#1]
- [x] Code structure... Create a directory named `src` for the code, `data` for input matrices
- [x] `src` -> `cspid.c`, `util.c` and eventually headers (.h files) Makefile. `cspid.c` should contain the main, and other routines for the computation. `utils.c` should contain routines for managing command line options, debugging and profiling
- [x] `data` -> put a couple of very tiny matrices. Ideally something that you can manually solve

**Comment by seharsyed** [comment]
successfully complied the examples and created 'Makefile' for the small test examples.
